### ISSUE TITLE
yarn leeds into error on Windows 10

### ISSUE THREAD

**Issue by nao3301** [authenio/react-samlify#5]
yarn retuns with error as shown below:

Error: Cannot find module 'libxmljs-mt'\r
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\r
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)\r
    at [eval]:1:33\r
    at Script.runInThisContext (vm.js:119:20)\r
    at Object.runInThisContext (vm.js:326:38)\r
    at Object.<anonymous> ([eval]-wrapper:6:22)\r
    at Module._compile (internal/modules/cjs/loader.js:701:30)\r
    at evalScript (internal/bootstrap/node.js:589:27)\r
    at startup (internal/bootstrap/node.js:265:9)\r
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)\r
gyp: Call to 'node -p -e \"require('path').dirname(require.resolve('libxmljs-mt'))\"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763

error C:\...\react-samlify-master\react-samlify-master\node_modules\samlify: Command failed.
Exit code: 1
Command: make validator
Arguments:
Directory: C\:...\react-samlify-master\react-samlify-master\node_modules\samlify

**Comment by tngan** [comment]
@nao3301 I will update to the latest samlify version soon.

**Comment by tngan** [comment]
@nao3301 Can you try again ? 

Known issue: SLO is not working after upgrade (logout okta side but not logout the service provider), will create another ticket for it.

**Comment by tngan** [comment]
Update: SLO should work

Feel free to reopen if needed.
